---
title: "Air Pollution Seoul"
output: ioslides_presentation
---

```{r setup, include=FALSE, eval = T}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "C:/Users/godzi/Documents/airpollutionseoul")
```

# Air Poluttion in Seoul:
### Below is a map showcasing the locations of the measuring stations:  

  
  

```{r cars, echo = FALSE, message = FALSE}

library(data.table)
library(mapview)
library(sf)
library(ggplot2)
library(gganimate)
library(leaflet)

station_info <- readRDS('./data/station_info.rds')
station_info_coords <- station_info[4:5]

themap <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng=station_info_coords$Longitude, lat = station_info_coords$Latitude)
themap


```

## The below map shows us the average values of each of the pollutants, per year. 

```{r, echo = FALSE}

mean_summary <- readRDS('./data/mean_summary.rds')

knitr::kable(mean_summary)

```
  
  
    
    

The below plot shows us through animation how the means have been changing for various pollutants. 

```{r, echo = FALSE}


mean_summary_pm <- readRDS('./data/mean_summary_pm.rds')
mean_summary_pol <- readRDS('./data/mean_summary_pol.rds')


mean_summary_pm_tidy <- melt(mean_summary_pm, id.vars = 'year')

mean_summary_pol_tidy <- melt(mean_summary_pol, id.vars = 'year')

pm_plot <- ggplot(mean_summary_pm_tidy, aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat='identity') +
  theme_bw() +
  transition_states(
    year,
    transition_length = 2,
    state_length = 1
  ) +
  ease_aes('sine-in-out')

```


``` {r, echo = FALSE}

animate(pm_plot)

```



```{r, echo = FALSE}

ggplot(mean_summary_pol_tidy, aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat='identity') +
  theme_bw() +
  transition_states(
    year,
    transition_length = 2,
    state_length = 1
  ) +
  ease_aes('sine-in-out')
getwd()

```

